#!/usr/bin/env bash
# uprds — update every PR of a MIP stack at once, each with a shared "Stack" section. just uprds #
# the stack of the current branch (mip-NNNN/*) just uprds MIP-0005 # that stack just uprds
# --dry-run # print every body, change nothing (no gh login needed) For each task branch, bottom
# of the stack first: the PR body is regenerated by scripts/uprd.sh (What changed + Cost from the
# branch's commits — the same body `just uprd` writes) and a "Stack" section is appended listing
# every PR of the MIP in merge order with its state, the current one marked, and the stack's
# summed Cost.
set -euo pipefail
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/uprd_title.sh.
source "$script_dir/lib/uprd_title.sh"
dry=0; mip=""
for a in "$@"; do case "$a" in --dry-run) dry=1 ;; *) mip="$a" ;; esac; done
cur="$(git branch --show-current)"
[ -n "$mip" ] || mip="$(sed -n 's#^\(mip-[0-9]\{4\}\)/.*#\1#p' <<<"$cur")"
[ -n "$mip" ] || { echo "uprds: not on a mip-NNNN/* branch — pass the MIP: just uprds MIP-0005" >&2; exit 1; }
mip="$(tr '[:upper:]' '[:lower:]' <<<"$mip")"
git fetch -q origin 2>/dev/null || true

# Every task branch of the MIP, local or remote, sorted by task number (scripts/stack.sh
# branches).
branches="$(scripts/stack.sh branches "$mip")"
[ -n "$branches" ] || { echo "uprds: no $mip/* branches" >&2; exit 1; }

task_of() { sed -n 's#^mip-[0-9]\{4\}/\([0-9]*\)-.*#\1#p' <<<"$1"; }
base_of() {   # task k's base is task k-1's branch, main for task 1
  local k; k="$(task_of "$1")"
  if [ "$k" -le 1 ]; then echo main; else grep "^$mip/$((k - 1))-" <<<"$branches" | head -1; fi
}
ref_of() { git rev-parse --verify -q "$1" >/dev/null && echo "$1" || echo "origin/$1"; }
cost_of() {   # sum of the numeric `Cost: ~$N` trailers on one branch, and the raw lines
  git log --format=%b "origin/$(base_of "$1")..$(ref_of "$1")" 2>/dev/null | sed -n 's/^Cost:[[:space:]]*//p'
}

# --- the shared Stack section ---------------------------------------------------------------.
stack_section() {   # $1 = the branch this body is for
  local me="$1" total=0 n=0 b pr line usd
  echo "**Stack — ${mip^^}** (merge order, base first)"
  echo
  while read -r b; do
    [ -n "$b" ] || continue
    n=$((n + 1))
    pr="$(gh pr view "$b" --json number,state,title -q '"#\(.number) \(.state) — \(.title)"' 2>/dev/null || echo "no PR yet")"
    line="$n. \`$b\` — $pr"
    [ "$b" = "$me" ] && line="$line **← this PR**"
    echo "$line"
    while read -r usd; do
      [ -n "$usd" ] || continue
      v="$(sed -n 's/^~\?\$\([0-9]*\.\?[0-9]*\).*/\1/p' <<<"$usd")"
      [ -n "$v" ] && total="$(awk -v a="$total" -v b="$v" 'BEGIN{printf "%.2f", a + b}')"
    done <<<"$(cost_of "$b")"
  done <<<"$branches"
  echo
  echo "Merge bottom-up; after each squash-merge run \`scripts/stack.sh restack\` on the next branch."
  echo "Stack cost so far: **~\$$total** (sum of every \`Cost:\` trailer in the stack; \`just cost-split ${mip^^}\` recomputes it from the session logs)."
}

# --- one PR per branch ----------------------------------------------------------------------.
while read -r b; do
  [ -n "$b" ] || continue
  base="$(base_of "$b")"
  extra="$(mktemp)"; stack_section "$b" > "$extra"
  if [ "$dry" -eq 1 ]; then
    echo "===== $b (base: $base) ====="
    BRANCH="$b" BASE="$base" EXTRA_FILE="$extra" scripts/uprd.sh --dry-run
    echo
  else
    if ! gh pr view "$b" --json number -q .number >/dev/null 2>&1; then
      git rev-parse --verify -q "origin/$b" >/dev/null || git push -q -u origin "$b"
    fi
    BRANCH="$b" BASE="$base" EXTRA_FILE="$extra" scripts/uprd.sh
    # Base and title follow the branch, not what the PR was opened with: a restacked lane gets its
    # new base, and a retitled tip commit renames the PR (same rule as uprd.sh's create path — the
    # first commit's subject on base..branch, capped at 70 chars, so every PR of the stack reads
    # "MIP-NNNN task k: …" without running past a skimmable length).
    first_subject="$(git log --reverse --format=%s "origin/$base..$(ref_of "$b")" 2>/dev/null | head -1)"
    title=""
    [ -n "$first_subject" ] && title="$(cap_title "$first_subject" "${mip^^}")"
    gh pr edit "$b" --base "$base" ${title:+--title "$title"} >/dev/null 2>&1 || true
  fi
  rm -f "$extra"
done <<<"$branches"

# GitHub's native Stack (the "Preview stack" box): `scripts/stack.sh link` — open PRs only, bottom
# to top; it explains itself when gh is not logged in or the extension is missing.
if [ "$dry" -eq 0 ]; then
  scripts/stack.sh link "$mip" || echo "uprds: GitHub Stack not linked (see above) — 'just stack-setup' then 'just stack-link ${mip^^}'" >&2
fi
